import React, { useEffect, useRef, useState } from "react";
import { createQuestion, evaluateAnswer, getHistory, login, register } from "./api";
const modes=[{id:"technical",icon:"⌘",title:"Техническое",text:"Навыки, код и решения"},{id:"hr",icon:"♢",title:"HR-интервью",text:"Опыт и коммуникация"},{id:"system",icon:"◫",title:"Системный дизайн",text:"Архитектура и масштаб"},{id:"english",icon:"A",title:"English",text:"Интервью на английском"},{id:"express",icon:"⚡",title:"Экспресс",text:"Один вопрос за 5 минут"}];
const roles=["Python Developer","Data Scientist","Frontend Developer","Product Manager"];
const Spinner=()=> <span className="spinner"/>;
export default function App(){
 const saved=JSON.parse(localStorage.getItem("career_user")||"null");
 const [tab,setTab]=useState("practice"),[stage,setStage]=useState("setup"),[role,setRole]=useState(""),[description,setDescription]=useState(""),[mode,setMode]=useState("technical"),[session,setSession]=useState(null),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[voice,setVoice]=useState(false),[seconds,setSeconds]=useState(300),[history,setHistory]=useState([]),[user,setUser]=useState(saved),[authMode,setAuthMode]=useState("login"),[credentials,setCredentials]=useState({username:"",password:""});
 const recognition=useRef(null),token=user?.token;
 useEffect(()=>{if(stage!=="question")return;const timer=setInterval(()=>setSeconds(x=>Math.max(0,x-1)),1000);return()=>clearInterval(timer)},[stage]);
 useEffect(()=>{if(user)loadHistory()},[user]);
 const run=async action=>{setLoading(true);setError("");try{await action()}catch(e){setError(e.message)}finally{setLoading(false)}};
 const loadHistory=()=>run(async()=>setHistory(await getHistory(token)));
 const begin=()=>run(async()=>{const data=await createQuestion(role,description,mode,token);setSession(data);setAnswer("");setSeconds(mode==="express"?180:300);setStage("question")});
 const submit=()=>run(async()=>{const data=await evaluateAnswer(session.id,answer,token);setFeedback(data);setStage("feedback");if(user)loadHistory()});
 const speak=()=>{if(!window.speechSynthesis)return setError("Озвучивание недоступно в этом браузере.");window.speechSynthesis.cancel();window.speechSynthesis.speak(new SpeechSynthesisUtterance(session.question))};
 const voiceInput=()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return setError("Голосовой ввод лучше всего работает в Chrome или Edge.");const r=new Recognition();r.lang=mode==="english"?"en-US":"ru-RU";r.interimResults=true;r.continuous=true;r.onstart=()=>setVoice(true);r.onresult=e=>setAnswer([...e.results].map(x=>x[0].transcript).join(" "));r.onerror=()=>{setVoice(false);setError("Не удалось распознать речь. Проверьте доступ к микрофону.")};r.onend=()=>setVoice(false);recognition.current=r;r.start()};
 const reset=()=>{setStage("setup");setSession(null);setFeedback(null);setAnswer("")};
 const auth=()=>run(async()=>{const r=authMode==="login"?await login(credentials.username,credentials.password):await register(credentials.username,credentials.password);const next={token:r.token,username:r.username};localStorage.setItem("career_user",JSON.stringify(next));setUser(next);setTab("progress")});
 const logout=()=>{localStorage.removeItem("career_user");setUser(null);setHistory([]);setTab("practice")};
 const avg=history.length?(history.reduce((s,x)=>s+(x.score||0),0)/history.length).toFixed(1):"—",today=history.filter(x=>new Date(x.created_at).toDateString()===new Date().toDateString()).length,time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 return <main><nav><div className="brand"><span>✦</span> Карьерный помощник</div><div className="desktop-nav"><button onClick={()=>setTab("practice")}>Тренировка</button><button onClick={()=>setTab("progress")}>Прогресс</button><button onClick={()=>setTab("profile")}>{user?user.username:"Профиль"}</button></div></nav><section className="shell">{error&&<div className="error"><span>!</span>{error}<button onClick={()=>setError("")}>×</button></div>}
 {tab==="practice"&&stage==="setup"&&<div className="card setup"><p className="eyebrow">ПОДГОТОВКА К ИНТЕРВЬЮ</p><h1>Оттачивайте ответы<br/>до <em>уверенного</em> уровня.</h1><p className="lead">Выберите формат — помощник подберёт вопрос и даст понятную обратную связь.</p><div className="mode-grid">{modes.map(x=><button className={mode===x.id?"mode active":"mode"} key={x.id} onClick={()=>setMode(x.id)}><b>{x.icon}</b><span>{x.title}<small>{x.text}</small></span></button>)}</div><label>Направление</label><div className="chips">{roles.map(x=><button className={role===x?"chip active":"chip"} onClick={()=>setRole(x)} key={x}>{x}</button>)}</div><input value={role} onChange={e=>setRole(e.target.value)} placeholder="Или укажите свою роль"/><label>Описание вакансии <small>необязательно</small></label><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Вставьте ключевые требования вакансии..." rows="4"/>{!user&&<p className="save-note">✦ Войдите в профиль, чтобы сохранять прогресс между устройствами.</p>}<button className="primary" disabled={!role.trim()||loading} onClick={begin}>{loading?<Spinner/>:"Начать тренировку →"}</button></div>}
 {tab==="practice"&&stage==="question"&&session&&<div className="card interview"><div className="question-top"><p className="eyebrow">{session.category||"ВОПРОС СОБЕСЕДОВАНИЯ"}</p><div className={seconds<60?"timer urgent":"timer"}>◷ {time}</div></div><h2>Ваша роль: <em>{role}</em></h2><div className="question"><span>?</span><p>{session.question}</p></div><div className="question-tools"><button onClick={speak}>🔊 Озвучить вопрос</button>{session.hint&&<span>💡 {session.hint}</span>}</div><label>Ваш ответ</label><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Расскажите о своём опыте или ходе решения..." rows="7"/><div className="answer-bar"><span>{answer.trim().split(/\s+/).filter(Boolean).length} слов</span>{voice?<button className="recording" onClick={()=>recognition.current?.stop()}>■ Завершить запись</button>:<button className="secondary" onClick={voiceInput}>🎙 Ответить голосом</button>}</div><div className="actions"><button className="text-btn" onClick={reset}>← К режимам</button><button className="primary" disabled={answer.trim().length<10||loading} onClick={submit}>{loading?<Spinner/>:"Получить оценку →"}</button></div></div>}
 {tab==="practice"&&stage==="feedback"&&feedback&&<div className="card feedback"><p className="eyebrow">РЕЗУЛЬТАТ ТРЕНИРОВКИ</p><div className="score"><strong>{feedback.score}</strong><span>/10<br/><small>оценка ответа</small></span></div><h2>{feedback.summary}</h2><div className="columns"><article><h3>✓ Сильные стороны</h3><ul>{feedback.strengths?.map((x,i)=><li key={i}>{x}</li>)}</ul></article><article><h3>↗ Что улучшить</h3><ul>{feedback.improvements?.map((x,i)=><li key={i}>{x}</li>)}</ul></article></div><article className="improved"><h3>Как мог бы звучать сильный ответ</h3><p>{feedback.improved_answer}</p></article><p className="tip">✦ {feedback.next_tip}</p><div className="actions"><button className="secondary" onClick={()=>{setTab("progress");if(user)loadHistory()}}>Мой прогресс</button><button className="primary" onClick={reset}>Новый вопрос →</button></div></div>}
 {tab==="progress"&&<div className="card progress-page"><p className="eyebrow">ВАШ ПРОГРЕСС</p><h2>Становитесь увереннее с каждой попыткой</h2>{!user?<div className="empty"><span>✦</span><h3>Прогресс ждёт вас</h3><p>Создайте профиль — и каждая тренировка будет сохранена.</p><button className="primary" onClick={()=>setTab("profile")}>Создать профиль</button></div>:<><div className="stats"><Stat label="тренировок" value={history.length}/><Stat label="средняя оценка" value={avg}/><Stat label="сегодня из 3" value={today}/></div>{history.length>1&&<ProgressChart history={history}/>}<h3>Недавние тренировки</h3>{history.length?<div className="history">{history.map(x=><div className="history-row" key={x.id}><span className="history-score">{x.score}</span><span><b>{x.role}</b><small>{x.question}</small></span><time>{new Date(x.created_at).toLocaleDateString("ru-RU")}</time></div>)}</div>:<p className="muted">Пока нет завершённых тренировок. Начните первую!</p>}</>}</div>}
 {tab==="profile"&&<div className="card profile"><p className="eyebrow">ПРОФИЛЬ</p>{user?<><div className="avatar">{user.username[0].toUpperCase()}</div><h2>{user.username}</h2><p className="lead">Ваши завершённые тренировки сохраняются в личной истории.</p><button className="secondary" onClick={logout}>Выйти из аккаунта</button></>:<><h2>Сохраняйте свой прогресс</h2><p className="lead">Создайте профиль, чтобы видеть историю и результаты на любом устройстве.</p><div className="auth-tabs"><button className={authMode==="login"?"active":""} onClick={()=>setAuthMode("login")}>Войти</button><button className={authMode==="register"?"active":""} onClick={()=>setAuthMode("register")}>Создать профиль</button></div><label>Имя</label><input value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})} placeholder="Например, Aigerim"/><label>Пароль</label><input type="password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})} placeholder="Минимум 6 символов"/><button className="primary" disabled={loading} onClick={auth}>{loading?<Spinner/>:authMode==="login"?"Войти":"Создать профиль"}</button></>}</div>}</section><nav className="bottom-nav"><button className={tab==="practice"?"active":""} onClick={()=>setTab("practice")}><span>◉</span>Тренировка</button><button className={tab==="progress"?"active":""} onClick={()=>setTab("progress")}><span>▥</span>Прогресс</button><button className={tab==="profile"?"active":""} onClick={()=>setTab("profile")}><span>◯</span>Профиль</button></nav></main>
}
function Stat({label,value}){return <div className="stat"><strong>{value}</strong><span>{label}</span></div>}
function ProgressChart({history}){const scores=[...history].reverse().slice(-12).map(x=>x.score||0),points=scores.map((score,i)=>`${i*(280/(scores.length-1))},${92-score*8}`).join(" ");return <div className="chart" style={{background:"#203029",borderRadius:12,padding:18,marginBottom:25}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><b>Динамика оценок</b><small>Последние тренировки</small></div><svg viewBox="0 0 280 100" role="img" aria-label="График оценок" style={{width:"100%",display:"block"}}><path d="M0 92H280" stroke="#496157"/><polyline points={points} fill="none" stroke="#58dfa8" strokeWidth="3"/>{scores.map((score,i)=><circle key={i} cx={i*(280/(scores.length-1))} cy={92-score*8} r="3" fill="#58dfa8"/>)}</svg></div>}
